openapi: 3.0.0
info:
  version: 1.0.0
  title: API docs
  description: API 문서
  license:
    name: MIT
servers:
  - url: 'https://cabi.dev.42cadet.kr'
paths:
  /auth/login:
    post:
      tags:
        - /auth/login
      summary: (intra 로그인에 대한 요청입니다.)
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /auth/login/callback:
    post:
      tags:
        - /auth/login/callback
      summary: (intra 로그인 시도 후 처리에 대한 요청입니다.)
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /auth/logout:
    post:
      tags:
        - /auth/logout
      summary: (intra 로그아웃에 대한 요청입니다.)
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/cabinet:
    post:
      tags:
        - /api/cabinet
      summary: (전체 사물함에 대한 정보입니다.)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cabinetList'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/lent_info:
    post:
      tags:
        - /api/lent_info
      summary: (현재 모든 대여자들의 정보입니다.)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/lentInfo'
                  - $ref: '#/components/schemas/isLent'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/lent:
    post:
      tags:
        - /api/lent
      summary: (특정 사물함을 빌릴 때 요청됩니다.)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - cabinet_id
                properties:
                  lent_id:
                    type: integer
                    example: 1
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/return_info:
    post:
      tags:
        - /api/return_info
      summary: (특정 사용자가 현재 대여하고 있는 사물함의 정보입니다.)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/lentCabinet'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
  /api/return:
    post:
      tags:
        - /api/return
      summary: (특정 사물함을 반납 할 때 요청됩니다.)
      responses:
        '200':
          $ref: '#/components/responses/SuccessResponse'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - lent_id
              properties:
                lent_id:
                  type: integer
                  example: 1
  /api/check:
    post:
      tags:
        - /api/check
      summary: (적절한 유저가 페이지를 접근하는지에 대한 정보입니다.)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/userInfo'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
components:
  parameters: null
  schemas:
    Error:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    Success:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    cabinetList:
      type: object
      required:
        - location
        - floor
        - section
        - cabinet
      properties:
        location:
          type: Array<string>
          example:
            - serom
            - maru
        floor:
          type: Array<Array<integer>>
        section:
          type: Array<Array<Array<string>>>
        cabinet:
          type: Array<Array<Array<Array<cabinetInfo>>>>
    lentInfo:
      type: object
      required:
        - lent_id
        - lent_cabinet_id
        - lent_user_id
        - lent_time
        - expire_time
        - extension
        - intra_id
      properties:
        lent_id:
          type: integer
          example: 1
        lent_cabinet_id:
          type: integer
          example: 1
        lent_user_id:
          type: integer
          example: 1
        lent_time:
          type: string
          example: '2022-01-22'
        expite_time:
          type: string
          example: '2022-02-22'
        extension:
          type: boolean
          example: true
        intra_id:
          type: string
          example: skim
    isLent:
      type: object
      required:
        - isLent
      properties:
        isLent:
          type: integer
          exmaple: 1
    lentCabinet:
      type: object
      required:
        - lent_id
        - lent_cabinet_id
        - lent_user_id
        - expire_time
        - extension
        - cabinet_num
        - location
        - floor
        - section
        - activation
      properties:
        lent_id:
          type: integer
          example: 1
        lent_cabinet_id:
          type: integer
          example: 1
        lent_user_id:
          type: integer
          example: 1
        expire_time:
          type: string
          format: datetime
          example: '2021-12-29'
        extension:
          type: boolean
          example: true
        cabinet_num:
          type: integer
          example: 1
        location:
          type: string
          example: serom
        floor:
          type: integer
          example: 1
        section:
          type: string
          example: oasis
        activation:
          type: boolean
          example: true
    userInfo:
      type: object
      required:
        - user_id
        - intra_id
        - auth
        - email
        - phone
        - access
        - refresh
      properties:
        user_id:
          type: integer
          example: 1
        intra_id:
          type: string
          example: skim
        auth:
          type: boolean
          example: true
        email:
          type: string
          example: skim@student.42seoul.kr
        phone:
          type: string
          example: 010-0000-0000
        access:
          type: string
          example: 1389fdsjklfsjkl
        refresh:
          type: string
          example: 2fjlksdflk02309
  responses:
    BadRequest:
      description: 잘못된 요청
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 잘못된 요청
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            success: false
            message: 서버 내부 오류
    SuccessResponse:
      description: 요청 성공
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Success'
          example:
            success: true
            message: 요청 성공
