version: '3'

services:
  mariadb:
    container_name: db
    build: ./
    restart: always
    environment:
      MARIADB_DATABASE_HOST: ${HOST}
      MARIADB_DATABASE: ${DATABASE}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${ROOT_PASSWORD}
    ports:
      - '3307:3306'
    tty: true
  gateway:
    container_name: nginx_gateway
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ~/yooh/dev/:/etc/nginx/conf.d/
