spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3310/test_db
    username: root
    password: test_password
  jpa:
    properties:
      hibernate:
        show_sql: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MariaDB103Dialect