name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: chmod update
        run: chmod 777 ./deploy.sh
      - name: run deploy.sh
        run: ./deploy.sh