name: CI

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: chmod update
        run: chmod 777 ./develop_front.sh
      - name: run develop_front.sh
        run: ./develop_front.sh

      - name: chmod update
        run: chmod 777 ./develop_back.sh
      - name: run develop_back.sh
        run: ./develop_back.sh